### ISSUE TITLE
Public mailing list

### ISSUE THREAD

**Issue by JohnnySheffield** [jxm262/xchange.js#5]
It would be cool to have access to a public mailing list without having to send a PM.

**Comment by jxm262** [comment]
@JohnnySheffield  done - https://groups.google.com/forum/#!forum/xchange  
Feel free to add this somewhere on the README as well, or else I'll get to it later this weekend

**Comment by jxm262** [comment]
will leave this ticket open until it's added to the readme

**Comment by JohnnySheffield** [comment]
Added the link to the mailing list in readme.md. Change available on #4
